name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Ensure Rust Windows GNU target
      run: rustup target add x86_64-pc-windows-gnu --toolchain stable

    - name: Build
      env:
        CARGO_TERM_COLOR: always
        RUSTFLAGS: "-C link-args=-Wl,--strip-debug"
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose

    - name: Prepare build artifacts
      run: |
        mkdir ${{ github.workspace }}\artifacts
        cp -Force ${{ github.workspace }}\target\x86_64-pc-windows-gnu\release\*.exe ${{ github.workspace }}\artifacts\
        cp -Force ${{ github.workspace }}\msys2.yml ${{ github.workspace }}\artifacts\
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: msys2-launcher-rs
        path: ${{ github.workspace }}\artifacts\
